-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 10:42:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teachersdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teachersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teachersdb` ;
USE `teachersdb` ;

-- -----------------------------------------------------
-- Table `teachersdb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teachersdb`.`courses` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `Teacher_Id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `teachersdb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teachersdb`.`students` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LASTNAME` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `FIRSTNAME` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `LASTNAME_IDX` (`LASTNAME` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13;


-- -----------------------------------------------------
-- Table `teachersdb`.`studentcourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teachersdb`.`studentcourse` (
  `course_ID` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`course_ID`, `student_id`),
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_ID`)
    REFERENCES `teachersdb`.`courses` (`Id`),
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `teachersdb`.`students` (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teachersdb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teachersdb`.`teachers` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Surrogate key',
  `LASTNAME` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `FIRSTNAME` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `LASTNAME-IDX` (`LASTNAME` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
